import type { Source } from '../types/chat';
import type { ResponseSources, InternalSource, WebSource, SourceConfidenceInfo } from '../types/aiResponse';
import { calculateSourceConfidence } from '../services/sourceConfidenceService';
import {
  PROVIDER_REGISTRY,
  legacyTypeToProviderId,
  getProvider,
  providerIdToLegacyType,
} from '../types/sourceNormalization';

// ============================================
// ENRICHED SOURCE DATA REGISTRY
// ============================================

/**
 * Source data registry with provider metadata
 * Includes Beroe reports, partner data, and market sources
 */
const SOURCE_DATA_REGISTRY: Record<string, Partial<InternalSource> & { providerId: string }> = {
  // ========== BEROE INTELLIGENCE (Tier 1) ==========
  'Beroe Risk Intelligence': {
    providerId: 'beroe_risk',
    reportId: 'beroe-risk-2024-q4',
    category: 'Risk Analytics',
    summary: 'Comprehensive supplier risk assessment covering financial stability, operational resilience, and compliance factors.',
  },
  'Portfolio Analytics': {
    providerId: 'beroe',
    reportId: 'beroe-portfolio-2024',
    category: 'Portfolio Management',
    summary: 'Portfolio-wide risk distribution and trend analysis with actionable recommendations.',
  },
  // Dynamic source names generated by Gemini
  'Portfolio Risk Analytics': {
    providerId: 'beroe_risk',
    reportId: 'beroe-portfolio-risk-2024',
    category: 'Portfolio Risk',
    summary: 'Real-time portfolio risk metrics including supplier concentration, geographic exposure, and category dependencies. Updated weekly with automated risk scoring.',
  },
  'Supplier Risk Database': {
    providerId: 'beroe_risk',
    reportId: 'beroe-supplier-db-2024',
    category: 'Supplier Intelligence',
    summary: 'Comprehensive supplier risk profiles covering 50,000+ global suppliers with financial health, operational capacity, and compliance status indicators.',
  },
  'Risk Monitoring System': {
    providerId: 'beroe_risk',
    reportId: 'beroe-monitoring-2024',
    category: 'Risk Monitoring',
    summary: 'Automated risk monitoring with real-time alerts for financial distress, operational disruptions, regulatory changes, and geopolitical events affecting your supply base.',
  },
  'Supplier Profile Data': {
    providerId: 'beroe',
    reportId: 'beroe-supplier-profiles',
    category: 'Supplier Profiles',
    summary: 'Detailed supplier profiles including company overview, financial metrics, certifications, geographic footprint, and historical performance data.',
  },
  'Commodity Price Indices': {
    providerId: 'beroe_pricing',
    reportId: 'beroe-commodity-indices-2024',
    category: 'Pricing Intelligence',
    summary: 'Proprietary commodity price indices tracking 1,200+ categories globally. Includes spot prices, forward curves, and regional variance analysis for procurement benchmarking.',
  },
  'Market Intelligence Reports': {
    providerId: 'beroe',
    reportId: 'beroe-market-reports-2024',
    category: 'Market Intelligence',
    summary: 'In-depth market analysis covering supply-demand dynamics, cost drivers, competitive landscape, and 12-month price forecasts by category and region.',
  },
  'Spend Analytics Platform': {
    providerId: 'beroe',
    reportId: 'beroe-spend-analytics-2024',
    category: 'Spend Intelligence',
    summary: 'AI-powered spend analysis connecting procurement data with market intelligence. Identifies savings opportunities, contract compliance gaps, and supplier rationalization targets.',
  },
  'Price Benchmarking Data': {
    providerId: 'beroe_pricing',
    reportId: 'beroe-benchmarks-2024',
    category: 'Price Benchmarking',
    summary: 'Category-specific price benchmarks comparing your contracted rates against market indices and peer company data. Includes should-cost models and negotiation guidance.',
  },
  'Supplier Performance Data': {
    providerId: 'beroe',
    reportId: 'beroe-performance-metrics',
    category: 'Performance Metrics',
    summary: 'Historical supplier performance trends including delivery, quality, and responsiveness scores.',
  },
  'Industry Benchmarks': {
    providerId: 'beroe',
    reportId: 'beroe-industry-benchmark-2024',
    category: 'Market Intelligence',
    summary: 'Industry-wide benchmarking data for supplier evaluation and comparison.',
  },
  'Risk Change Alerts': {
    providerId: 'beroe_risk',
    reportId: 'beroe-alerts-digest',
    category: 'Alerts & Monitoring',
    summary: 'Recent risk score changes and triggering events across your monitored suppliers.',
  },
  'Category Intelligence Report': {
    providerId: 'beroe',
    reportId: 'beroe-category-q4-2024',
    category: 'Category Insights',
    summary: 'Deep-dive analysis into category trends, pricing dynamics, and market outlook.',
  },
  'Beroe Pricing Index': {
    providerId: 'beroe_pricing',
    reportId: 'beroe-pricing-index-2024',
    category: 'Pricing Intelligence',
    summary: 'Real-time pricing benchmarks across 1,200+ categories with regional indices.',
  },

  // ========== COMMODITY REPORTS (Tier 1 - Beroe) ==========
  'Aluminum Market Report 2024': {
    providerId: 'beroe',
    reportId: 'beroe-aluminum-2024',
    category: 'Commodity Intelligence',
    summary: 'Global aluminum market analysis including supply-demand dynamics, pricing forecasts, and regional trends.',
  },
  'Steel Market Intelligence': {
    providerId: 'beroe',
    reportId: 'beroe-steel-2024',
    category: 'Commodity Intelligence',
    summary: 'Hot rolled coil pricing trends, capacity utilization, and trade flow analysis.',
  },
  'Copper Supply Analysis': {
    providerId: 'beroe',
    reportId: 'beroe-copper-2024',
    category: 'Commodity Intelligence',
    summary: 'Copper market fundamentals with mine production forecasts and demand drivers.',
  },
  'Energy Markets Brief': {
    providerId: 'beroe',
    reportId: 'beroe-energy-2024',
    category: 'Commodity Intelligence',
    summary: 'Natural gas and electricity market dynamics across key regions.',
  },
  'Packaging Materials Outlook': {
    providerId: 'beroe',
    reportId: 'beroe-packaging-2024',
    category: 'Commodity Intelligence',
    summary: 'Corrugated, plastics, and sustainable packaging cost trends.',
  },

  // ========== FINANCIAL DATA (Tier 2) ==========
  'D&B Financial Data': {
    providerId: 'dun_bradstreet',
    reportId: 'dnb-financial-report',
    category: 'Financial Analysis',
    summary: 'Dun & Bradstreet credit and financial health indicators for supplier evaluation.',
  },
  'D&B Credit Rating': {
    providerId: 'dun_bradstreet',
    reportId: 'dnb-credit-rating',
    category: 'Credit Risk',
    summary: 'PAYDEX scores and credit limit recommendations based on payment history.',
  },
  "Moody's Credit Opinion": {
    providerId: 'moodys',
    reportId: 'moodys-credit-2024',
    category: 'Credit Risk',
    summary: 'Credit rating and outlook with financial strength assessment.',
  },
  'S&P Global Rating': {
    providerId: 'sp_global',
    reportId: 'sp-rating-2024',
    category: 'Credit Risk',
    summary: 'Long-term issuer credit rating with industry comparison.',
  },

  // ========== ESG DATA (Tier 2) ==========
  'EcoVadis Sustainability': {
    providerId: 'ecovadis',
    reportId: 'ecovadis-sustainability-2024',
    category: 'ESG & Sustainability',
    summary: 'Environmental, social, and governance performance ratings and improvement areas.',
  },
  'EcoVadis Carbon Scorecard': {
    providerId: 'ecovadis',
    reportId: 'ecovadis-carbon-2024',
    category: 'Environmental',
    summary: 'Carbon footprint assessment with scope 1, 2, and 3 emissions tracking.',
  },

  // ========== MARKET DATA (Tier 2) ==========
  'LME Aluminum Prices': {
    providerId: 'lme',
    reportId: 'lme-aluminum-spot',
    category: 'Market Data',
    summary: 'London Metal Exchange aluminum spot and forward prices.',
  },
  'LME Copper Prices': {
    providerId: 'lme',
    reportId: 'lme-copper-spot',
    category: 'Market Data',
    summary: 'London Metal Exchange copper spot and forward prices.',
  },
  'COMEX Gold Futures': {
    providerId: 'comex',
    reportId: 'comex-gold-futures',
    category: 'Market Data',
    summary: 'COMEX gold futures prices and open interest.',
  },
  'ICE Brent Crude': {
    providerId: 'ice',
    reportId: 'ice-brent-spot',
    category: 'Market Data',
    summary: 'ICE Brent crude oil spot and futures prices.',
  },
  'Henry Hub Natural Gas': {
    providerId: 'ice',
    reportId: 'ice-natgas-spot',
    category: 'Market Data',
    summary: 'Henry Hub natural gas spot and forward curve.',
  },

  // ========== TRADE INTELLIGENCE (Tier 2) ==========
  'Panjiva Trade Data': {
    providerId: 'panjiva',
    reportId: 'panjiva-trade-analysis',
    category: 'Trade Intelligence',
    summary: 'Import/export shipment records and trade flow analysis.',
  },
  'ImportGenius Analysis': {
    providerId: 'import_genius',
    reportId: 'importgenius-report',
    category: 'Trade Intelligence',
    summary: 'Bill of lading data and supplier discovery intelligence.',
  },

  // ========== INTERNAL DATA (Tier 2) ==========
  'Supplier Master Data': {
    providerId: 'supplier_data',
    reportId: 'internal-supplier-master',
    category: 'Internal Data',
    summary: 'Internal supplier records including contacts, certifications, and performance history.',
  },
  'Spend Analytics': {
    providerId: 'internal_data',
    reportId: 'internal-spend-analytics',
    category: 'Internal Data',
    summary: 'Historical spend data by category, supplier, and business unit.',
  },
  'Contract Repository': {
    providerId: 'internal_data',
    reportId: 'internal-contracts',
    category: 'Internal Data',
    summary: 'Active contract terms, pricing, and renewal dates.',
  },
};

// Legacy alias for backward compatibility
const MOCK_BEROE_REPORTS = SOURCE_DATA_REGISTRY;

export const normalizeUrl = (url: string): string => {
  const trimmed = url.trim();
  if (!trimmed) return trimmed;

  try {
    const parsed = new URL(trimmed);
    const pathname = parsed.pathname.replace(/\/$/, '');
    return `${parsed.origin}${pathname}${parsed.search}`;
  } catch {
    return trimmed;
  }
};

export const extractDomain = (url: string): string => {
  try {
    return new URL(url).hostname.replace(/^www\./, '');
  } catch {
    return 'source';
  }
};

/**
 * Map legacy source type to internal source type with provider metadata
 * Returns both the legacy type (for confidence calculation) and enriched provider info
 */
interface MappedSourceInfo {
  type: InternalSource['type'];
  providerId: string;
  providerShortName: string;
  reliabilityTier: 'tier1' | 'tier2' | 'tier3';
  sourceCategory: InternalSource['sourceCategory'];
  providerColor: string;
}

const mapInternalType = (type?: Source['type']): MappedSourceInfo | null => {
  // Get provider ID from legacy type
  const providerId = legacyTypeToProviderId(type);

  // Unknown types return null - drop rather than misclassify
  if (providerId === null) return null;

  const provider = getProvider(providerId);
  if (!provider) return null;

  // Map to legacy type for backward compatibility (confidence calculation)
  // Returns null for web/news sources that should NOT be internal
  const legacyType = providerIdToLegacyType(providerId);

  // If legacyType is null, this source should remain as web, not internal
  if (legacyType === null) return null;

  return {
    type: legacyType,
    providerId: provider.id,
    providerShortName: provider.shortName,
    reliabilityTier: provider.reliabilityTier,
    sourceCategory: provider.category as InternalSource['sourceCategory'],
    providerColor: provider.color || '#64748B',
  };
};

export interface BuildResponseSourcesOptions {
  /** Detected category from query for confidence calculation */
  detectedCategory?: string;
  /** User's managed categories for confidence calculation */
  managedCategories?: string[];
  /** Whether to calculate confidence (default: true) */
  calculateConfidenceFlag?: boolean;
}

/**
 * Enrich an internal source with provider metadata if missing
 * Used when sources arrive pre-built but without full metadata
 */
const enrichInternalSource = (source: InternalSource): InternalSource => {
  // If already has provider metadata, return as-is
  if (source.providerId && source.providerShortName && source.reliabilityTier) {
    return source;
  }

  // Get mapped info from legacy type
  const mappedInfo = mapInternalType(source.type);
  if (!mappedInfo) return source;

  // Enrich with source registry data if available
  const registryData = SOURCE_DATA_REGISTRY[source.name];

  // Build enriched source, preserving existing fields
  const enriched: InternalSource = {
    ...source,
    // Add provider metadata if missing
    providerId: source.providerId || registryData?.providerId || mappedInfo.providerId,
    providerShortName: source.providerShortName || mappedInfo.providerShortName,
    reliabilityTier: source.reliabilityTier || mappedInfo.reliabilityTier,
    sourceCategory: source.sourceCategory || mappedInfo.sourceCategory,
    providerColor: source.providerColor || mappedInfo.providerColor,
  };

  // If registry has a specific providerId, get more detailed metadata
  if (registryData?.providerId && registryData.providerId !== mappedInfo.providerId) {
    const specificProvider = getProvider(registryData.providerId);
    if (specificProvider) {
      enriched.providerId = specificProvider.id;
      enriched.providerShortName = specificProvider.shortName;
      enriched.reliabilityTier = specificProvider.reliabilityTier;
      enriched.sourceCategory = specificProvider.category as InternalSource['sourceCategory'];
      enriched.providerColor = specificProvider.color || enriched.providerColor;
    }
  }

  return enriched;
};

export const buildResponseSources = (
  sources: Source[] | ResponseSources | undefined | null,
  options?: BuildResponseSourcesOptions
): ResponseSources => {
  const { detectedCategory, managedCategories, calculateConfidenceFlag = true } = options || {};

  // Guard: if sources is already a ResponseSources object, enrich internal sources
  // with provider metadata if missing, then return
  if (sources && typeof sources === 'object' && 'web' in sources && 'internal' in sources) {
    const existing = sources as ResponseSources;

    // Enrich internal sources with provider metadata if missing
    if (existing.internal && existing.internal.length > 0) {
      existing.internal = existing.internal.map(enrichInternalSource);
    }

    if (!existing.confidence && calculateConfidenceFlag) {
      existing.confidence = calculateSourceConfidence(existing, detectedCategory, managedCategories);
    }
    return existing;
  }

  // Guard: if sources is not an array, return empty
  if (!Array.isArray(sources)) {
    const empty: ResponseSources = { web: [], internal: [], totalWebCount: 0, totalInternalCount: 0 };
    if (calculateConfidenceFlag) {
      empty.confidence = calculateSourceConfidence(empty, detectedCategory, managedCategories);
    }
    return empty;
  }

  const web: WebSource[] = [];
  const internal: InternalSource[] = [];
  const seenWeb = new Set<string>();
  const seenInternal = new Set<string>();

  for (const source of sources) {
    if (source.url) {
      const normalized = normalizeUrl(source.url);
      if (seenWeb.has(normalized)) continue;
      seenWeb.add(normalized);
      const domain = extractDomain(source.url);
      web.push({
        name: source.name || domain,
        url: source.url,
        domain,
        date: source.date,
      });
      continue;
    }

    if (!source.name) continue;
    const mappedInfo = mapInternalType(source.type);
    if (!mappedInfo) continue;

    const key = `${mappedInfo.type}:${source.name}`.toLowerCase();
    if (seenInternal.has(key)) continue;
    seenInternal.add(key);

    // Enrich with source registry data if available
    const registryData = SOURCE_DATA_REGISTRY[source.name];

    // Build enriched internal source
    const enrichedSource: InternalSource = {
      name: source.name,
      type: mappedInfo.type, // Legacy type for confidence calculation
      // Provider metadata from registry or mapped info
      providerId: registryData?.providerId || mappedInfo.providerId,
      providerShortName: mappedInfo.providerShortName,
      reliabilityTier: mappedInfo.reliabilityTier,
      sourceCategory: mappedInfo.sourceCategory,
      providerColor: mappedInfo.providerColor,
      // Report data from registry
      ...(registryData && {
        reportId: registryData.reportId,
        category: registryData.category,
        summary: registryData.summary,
      }),
    };

    // If registry has a specific providerId, update metadata from that provider
    if (registryData?.providerId && registryData.providerId !== mappedInfo.providerId) {
      const specificProvider = getProvider(registryData.providerId);
      if (specificProvider) {
        enrichedSource.providerId = specificProvider.id;
        enrichedSource.providerShortName = specificProvider.shortName;
        enrichedSource.reliabilityTier = specificProvider.reliabilityTier;
        enrichedSource.sourceCategory = specificProvider.category as InternalSource['sourceCategory'];
        enrichedSource.providerColor = specificProvider.color || '#64748B';
        // Keep legacy type as 'beroe' if it's a Beroe property (for confidence)
        if (specificProvider.isBeroeProperty) {
          enrichedSource.type = 'beroe';
        }
      }
    }

    internal.push(enrichedSource);
  }

  const result: ResponseSources = {
    web,
    internal,
    totalWebCount: web.length,
    totalInternalCount: internal.length,
  };

  // Calculate confidence if enabled
  if (calculateConfidenceFlag) {
    result.confidence = calculateSourceConfidence(result, detectedCategory, managedCategories);
  }

  return result;
};

/**
 * Create enriched internal sources with full provider metadata
 * Filters out any sources that should remain as web sources (news, web)
 */
export const createEnrichedSources = (
  sourceNames: string[]
): InternalSource[] => {
  return sourceNames
    .map(name => {
      const registryData = SOURCE_DATA_REGISTRY[name];
      const providerId = registryData?.providerId || 'beroe';
      const provider = getProvider(providerId);
      const legacyType = providerIdToLegacyType(providerId);

      // Skip sources that should remain as web sources
      if (legacyType === null) return null;

      return {
        name,
        type: legacyType,
        providerId: provider.id,
        providerShortName: provider.shortName,
        reliabilityTier: provider.reliabilityTier,
        sourceCategory: provider.category as InternalSource['sourceCategory'],
        providerColor: provider.color || '#64748B',
        ...(registryData && {
          reportId: registryData.reportId,
          category: registryData.category,
          summary: registryData.summary,
        }),
      };
    })
    .filter((s): s is InternalSource => s !== null);
};

// Legacy alias for backward compatibility
export const createEnrichedBeroeSources = createEnrichedSources;

/**
 * Create a standard set of sources for a given context
 * Returns enriched sources with full provider metadata
 */
export const getDefaultBeroeSources = (
  context: 'risk' | 'portfolio' | 'supplier' | 'category' | 'inflation' | 'pricing' | 'commodity'
): InternalSource[] => {
  const sourcesByContext: Record<string, string[]> = {
    risk: ['Beroe Risk Intelligence', 'Industry Benchmarks'],
    portfolio: ['Beroe Risk Intelligence', 'Portfolio Analytics'],
    supplier: ['Beroe Risk Intelligence', 'D&B Financial Data', 'EcoVadis Sustainability'],
    category: ['Category Intelligence Report', 'Industry Benchmarks'],
    inflation: ['Aluminum Market Report 2024', 'Category Intelligence Report'],
    pricing: ['Beroe Pricing Index', 'LME Aluminum Prices', 'Category Intelligence Report'],
    commodity: ['Aluminum Market Report 2024', 'LME Aluminum Prices', 'Steel Market Intelligence'],
  };

  return createEnrichedSources(sourcesByContext[context] || sourcesByContext.risk);
};

/**
 * Get all available source names from the registry
 */
export const getAvailableSourceNames = (): string[] => {
  return Object.keys(SOURCE_DATA_REGISTRY);
};

/**
 * Get sources by provider ID
 */
export const getSourcesByProvider = (providerId: string): InternalSource[] => {
  const matchingNames = Object.entries(SOURCE_DATA_REGISTRY)
    .filter(([, data]) => data.providerId === providerId)
    .map(([name]) => name);
  return createEnrichedSources(matchingNames);
};

/**
 * Get sources by reliability tier
 */
export const getSourcesByTier = (tier: 'tier1' | 'tier2' | 'tier3'): InternalSource[] => {
  const matchingNames = Object.entries(SOURCE_DATA_REGISTRY)
    .filter(([, data]) => {
      const provider = getProvider(data.providerId);
      return provider.reliabilityTier === tier;
    })
    .map(([name]) => name);
  return createEnrichedSources(matchingNames);
};

/**
 * Get report data for a source by name
 * Returns summary and other metadata for report viewer
 */
export const getSourceReportData = (sourceName: string): {
  summary?: string;
  reportId?: string;
  category?: string;
} | null => {
  const data = SOURCE_DATA_REGISTRY[sourceName];
  if (!data) return null;
  return {
    summary: data.summary,
    reportId: data.reportId,
    category: data.category,
  };
};
